### ISSUE TITLE
MPU6050 library nor working with esp core > 2.3.0

### ISSUE THREAD

**Issue by kevinlhoste** [josephlarralde/movuino-firmware#7]
**Settings :** 
[Esp core version] : 2.6.2

**Error :**  
for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH)) {
deduced conflicting types for parameter 'const _Tp' ('unsigned char' and 'int')
